### PR TITLE
Bug 1887373: Add leader election mechanism to release-4.5

### PR DESCRIPTION
**Pull request by andymcc**
This cherry-picks the fix from master/4.6 and integrates with:
https://github.com/openshift/machine-api-operator/pull/664

Adding 3 new cli arguments for configuring leader elections:
-leader-elect
-leader-elect-lease-duration int
-leader-elect-resource-namespace string

Using leader election will add stronger guarantees than we have today
that only one controller is running at a time to protect against edge
cases where the deployment replica could be increased or upgrades with
permissive maxSurge.

(cherry picked from commit 5ccc9929b421a57699e078681a490a6977c57a35)

### CODE REVIEW

**Review by cfergeau — APPROVED** [review]

**Comment by Prashanth684** [comment]
e2e-libvirt passed. @praveenkumar @cfergeau can one of you add an approval ?

**Review by cfergeau — APPROVED** [review]

**Pull request merged**
