### PR TITLE
Update dependencies and remove libvirt-actuator binary

### PR DESCRIPTION
**Pull request by Prashanth684**
Update dependencies to use latest k8s packages and machine-api-operator. And in doing so, refactor code to use machine-api-operator instead of the deprecated openshift/cluster-api. The libvirt-actuator binary is also removed as it was using the old cluster-api.

Cherry-picked commits from @cfergeau's branch:
https://github.com/cfergeau/cluster-api-provider-libvirt/commit/7de23e350ee616e3a7f0b29422e636f2e36c643b
https://github.com/cfergeau/cluster-api-provider-libvirt/commit/07237b9c020d45c8fb2528e0b0d388d969c50862
https://github.com/cfergeau/cluster-api-provider-libvirt/commit/ae0d426a140c777de2af053d0f4e6ceb865b3c41
squashed: https://github.com/cfergeau/cluster-api-provider-libvirt/commit/c50c9c0ab379270255559f3bfc45cd0e7fbcc898 and https://github.com/cfergeau/cluster-api-provider-libvirt/commit/027035428cba68e6fe94688b5e63e1e6c836f59c

The last commit adds liveness and readiness probes so the controller returns a 200 to the machine-api-operator which recently adds liveness and readiness checks.

Closes: #197

### CODE REVIEW

**Comment by cfergeau** [comment]
CI is failing because it's not using golang 1.13 to build cluster-api-provider-libvirt. This will be addressed by https://github.com/openshift/release/pull/10066

**Comment by JoelSpeed** [comment]
@Prashanth684 Was this PR meant to be linked to https://bugzilla.redhat.com/show_bug.cgi?id=1831780? Do you know if we can retitle now to add the bug description so we can get  the BZ automation to move to QE to verify this fixed it?

**Comment by JoelSpeed** [comment]
/retitle Bug 1831780: Update dependencies and remove libvirt-actuator binary

**Comment by Prashanth684** [comment]
> @Prashanth684 Was this PR meant to be linked to https://bugzilla.redhat.com/show_bug.cgi?id=1831780? Do you know if we can retitle now to add the bug description so we can get the BZ automation to move to QE to verify this fixed it?

@JoelSpeed yeah this was one of the issues that was fixed by this PR as well. But the main reason for this PR was the libvirt controller was continuously crashing because the health checks failed and that needed the packages to be updated which also fixed 1831780. But linking it to 1831780 is fine too! thanks!

**Pull request merged**
