### PR TITLE
Allow to specify an ignition configuration through user secret

### PR DESCRIPTION
**Pull request by ingvagabund**
To build:
```
$ make libvirt-actuator
```

To create:
```
$ ./bin/libvirt-actuator --logtostderr create --cluster examples/cluster.yaml --machine examples/machine-with-userdata.yml  --userdata examples/ignition-userdata.yml
```

To delete:
```
$ ./bin/libvirt-actuator delete --cluster examples/cluster.yaml --machine examples/machine-with-userdata.yml  --userdata examples/ignition-userdata.yml --logtostderr
```

### CODE REVIEW

**Comment by ingvagabund** [comment]
Still having issues with:
```
E1031 17:14:36.801738   24620 actuator.go:47] tb-asg-35/worker-example: error creating libvirt machine: error creating domain: error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: early end of file from monitor, possible problem: 2018-10-31T16:14:36.555216Z qemu-system-x86_64: -fw_cfg name=opt/com.coreos/config,file=/var/lib/libvirt/images/worker.ign: can't load /var/lib/libvirt/images/worker.ign')
```
Not sure what is wrong atm

**Comment by wking** [comment]
`can't load` [might be SELinux][1].

[1]: https://github.com/dmacvicar/terraform-provider-libvirt/issues/142#issuecomment-409040151

**Comment by ingvagabund** [comment]
> can't load might be SELinux.

Yes, it is!!!!!!!!

**Comment by ingvagabund** [comment]
So I am able to create an ignition volume.

**Comment by bison** [comment]
/lgtm

We have to create a `CreateDomainOptions` struct at some point... The signature for `CreateDomain()` is crazy.

**Pull request merged**
