### PR TITLE
remove copyright notice

### PR DESCRIPTION
**Pull request by paulfantom**
Part of CLOUD-244

### CODE REVIEW

**Comment by ingvagabund** [comment]
We should generate diffferent boillerplare header since we need to express the projects resources are under ASL 2.0 license.

**Comment by paulfantom** [comment]
Ideas on a content of such boilerplate? If we just want to say that this is using ASL 2.0, so maybe only SPDX header?

**Comment by paulfantom** [comment]
Also whole repo is ASL 2.0 :)

**Pull request merged**
