### PR TITLE
Update packet image

### PR DESCRIPTION
**Pull request by paulfantom**
Image was build and is stored in https://github.com/paulfantom/packet-image

/assign @ingvagabund

### CODE REVIEW

**Comment by enxebre** [comment]
we need to:
- revendor the framework to pick the crd status fixes
- Update the client calls to updaStatus
- Update `hack/prebulid/init.sh` to pin to kube version 1.11.3

**Comment by paulfantom** [comment]
> revendor the framework to pick the crd status fixes

Framework is in latest version.

**Pull request merged**
