### PR TITLE
replace glog with logrus

### PR DESCRIPTION
**Pull request by paulfantom**
SSIA

Part of CLOUD-218

### CODE REVIEW

**Comment by paulfantom** [comment]
Also switching to `SJC1` packet datacenter as `EWR1` is frequently full and not able to provision `c1.small` machines.

**Comment by frobware** [comment]
> Also switching to `SJC1` packet.net datacenter as `EWR1` is frequently full and not able to provision `c1.small` machines.

We should do this as a separate PR as they're not related. If you ever wanted to revert this change you'd have to deal with the loss of glog -> logrus.

**Comment by frobware** [comment]
> What do you mean?

It's just good commit hygiene. If your commit/PR did just one thing it's trivial to revert.

**Comment by paulfantom** [comment]
Just had to decide on one and logrus seemed like a better choice :stuck_out_tongue:

**Comment by ingvagabund** [comment]
> Just had to decide on one and logrus seemed like a better choice :stuck_out_tongue: 

alt

**Comment by paulfantom** [comment]
Did more research and it is 50-50, half prefer glog another half prefer logrus. So...
alt

**Pull request closed without merging**
