### PR TITLE
Implement leader election for manager

### PR DESCRIPTION
**Pull request by andymcc**
This adds integration with:
https://github.com/openshift/machine-api-operator/pull/571

### CODE REVIEW

**Comment by andymcc** [comment]
Thanks! I've added some more context based on the PRs that went into the other api-providers.

**Comment by cfergeau** [comment]
Bad news is that I have no idea what's going on with CI :(
/test e2e-libvirt

**Comment by andymcc** [comment]
Thanks @cfergeau - may have been luck that it passed but glad it's in!

**Pull request merged**
