### PR TITLE
fix golint issues

### PR DESCRIPTION
**Pull request by enxebre**

### CODE REVIEW

**Comment by ingvagabund** [comment]
```
pkg-config --cflags libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt
```

That is nice.

**Comment by ingvagabund** [comment]
`ci/prow/unit`:
```
[Errno 13] Permission denied: '/var/lib/rpm/.dbenv.lock'
--
  | You need to be root to perform this command.
```

**Comment by enxebre** [comment]
vet/unit need to be solved ensuring the cgo deps are installer during the CI tasks

**Comment by paulfantom** [comment]
> vet/unit need to be solved

More info why those are failing: https://github.com/openshift/release/pull/1426#issuecomment-420977138

**Pull request merged**
