### PR TITLE
OCPBUGS-26046: Replace genisoimage with xorriso in 4.15 to allow rhel9 bump

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by praveenkumar** [comment]
/retilte OCPBUGS-26046: Replace genisoimage with xorriso in 4.15 to allow rhel9 bump

**Comment by praveenkumar** [comment]
/retitle OCPBUGS-26046: Replace genisoimage with xorriso in 4.15 to allow rhel9 bump

**Review by gbraad — APPROVED** [review]

**Pull request merged**
